# Generated by Django 5.0.6 on 2024-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video_480p', models.CharField(blank=True, max_length=255, null=True)),
                ('video_720p', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
